- package-lock.json
- package.json
- public/index.html
- src/components/commons/Header.js
- src/components/commons/Sidebar.js
- src/components/contents/ApprovalBox.js
- src/components/contents/ButtonGroup.js
- src/components/contents/Editor.js
- src/components/contents/ScheduleBox.js
- src/components/contents/TitleAndFile.js
- src/pages/Main.js
- src/pages/notices/InsertNotice.js
- src/pages/notices/Notices.js
0503-11시45분-hjk -> main
main, 컴포넌트 추가 및 수정
main, 컴포넌트 추가 및 수정 화면 확인됨
#1
> [Feature-0503](#1) - main, 컴포넌트 추가 및 수정

- public/index.html
- src/apis/Api.js
- src/apis/NoticeAPICalls.js
- src/components/contents/BootstrapTable.js
- src/components/contents/Editor.js
- src/components/contents/TitleAndFile.js
- src/index.js
- src/modules/NoticeModule.js
- src/modules/index.js
- src/pages/Main.js
- src/pages/notices/InsertNotice.js
- src/pages/notices/Notices.js
- src/style.css
- src/utils/tokenUtils.js
0507-12시40분-hjk -> main
공지 목록조회(상단고정, 등록 역순)
공지목록조회 성공
#7
> [Feature-0507](#7) - notice- 공지목록조회

- package-lock.json
- package.json
- src/App.js
- src/Store.js
- src/apis/Api.js
- src/apis/ScheduleAPICalls.js
- src/components/form/ScheduleForm.js
- src/modules/ScheduleModule.js
- src/modules/index.js
- src/pages/schedules/calendar.js
Jay-20240507-v1
부서별 일정 목록 조회
- db에서 일정 데이터를 가져오기 위해서 initialEvents 속성 대신 events 속성을 사용하였습니다.
- db에 저장된 날짜 데이터를 ISO8601으로 변환해줘야 full calendar에서 인식하기 때문에 moment라는 라이브러리 설치하였습니다.
#이슈번호
#11
> [Feature-0507](#11) - calendar - 부서별 일정 목록 조회

- README.md
- package-lock.json
- package.json
- src/App.js
- src/apis/Api.js
- src/apis/MemberAPICalls.js
- src/components/commons/Header.js
- src/modules/MemberModule.js
- src/modules/index.js
- src/pages/Main.js
- src/pages/members/Login.js
ex) 240508-hoo-1 -> main
ex) 로그인과 토큰저장 기능을 추가하였습니다.
ex) localhost:3000/login으로 진행하시면 됩니다.
#15
> [Feature-0508](#15) - 리액트 로그인 구현

- package-lock.json
- src/apis/ApprovalAPICalls.js
- src/components/approvals/AppLine.js
- src/components/approvals/AppLine.module.css
- src/components/approvals/RefLine.js
- src/pages/approvals/ApprovalDetail.js
- src/pages/approvals/Approvals.js
- src/pages/approvals/Approvals.module.css
0509seung -> main
기안 상세 조회 결재선, 참조선 추가
새로고침하면 에러나는 이슈있음 수정필요
#25
>  [Feature-0509](#25) - 기안조회 - 기안상세조회   

- src/apis/NoticeAPICalls.js
- src/components/contents/SearchBar.js
- src/components/items/notices/Notice.js
- src/pages/notices/Notices.js
0511-11시50분-hjk -> main
공지 목록 검색 조회 시 검색어가 포함된 공지 목록 조회
검색어가 포함된 목록조회 성공
#7
>  [Feature-0511](#7) - notice - 공지 목록조회 검색기능 수정

- package-lock.json
- src/apis/ApprovalAPICalls.js
- src/components/approvals/AppCategory.js
- src/components/approvals/AppCategory.module.css
- src/components/approvals/AppLine.js
- src/components/approvals/AppLineModal.js
- src/components/approvals/AppList.js
- src/components/approvals/AppModal.module.css
- src/components/approvals/RefLine.js
- src/components/approvals/RefLineModal.js
- src/pages/approvals/ApprovalDetail.js
- src/pages/approvals/Approvals.js
- src/pages/approvals/InsertApproval.js
0513seung -> main
결재선, 참조선 모달 등 
결재선 참조선 저장까지 결과 확인 추후 검색 기능 추가 필요및 등록 테스트 필요
#6
> [Feature-MMDD](#6) - InsertApproval - 전자결재 등록

- package-lock.json
- src/apis/MailAPICalls.js
- src/components/contents/MailTable.js
- src/components/contents/SearchBarValue.js
- src/components/form/InsertNoticeForm.js
- src/components/form/MailForm.js
- src/modules/MailModule.js
- src/pages/mails/Mail.js
- src/pages/mails/MailDetail.js
- src/pages/mails/mail.css
- src/style.css
- 제목 : [Feature-MMDD](issue 번호) - 기능명 - 간단설명
ex) [Feature-0510](#3) - board - 간단설명
ex) [Bug-MMDD](issue 번호) - 기능명
ex) [Custom-MMDD](issue 번호) - 기능명
(확인 후 지워주세요)
ex) 0510-4시-hjk -> main
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
#이슈번호
> [Feature-MMDD](issue 번호) - 기능명 - 간단설명

- src/App.js
- src/apis/MailAPICalls.js
- src/components/form/MailForm.js
- src/components/items/mails/MailTable.js
- src/components/items/mails/MailTableBody.js
- src/components/lists/mails/ReceiveMail.js
- src/components/lists/mails/SendMail.js
- src/modules/MailModule.js
- src/pages/mails/Mail.js
- src/pages/mails/mail.css
0515-6시50분-pde -> main
- 메일 읽음 상태 변경합니다.
- 받은 메일 조회 목록에서 읽음 상태일때는 글씨가 얇은 출력되고, 안읽음 상태일때는 글씨가 두껍게 출력됩니다.
#74
> [Feature-0515](#74) - 메일 - 메일 읽음 상태 변경

- src/apis/MailAPICalls.js
- src/components/items/mails/MailContent.js
- src/components/items/mails/MailDeleteModal.js
- src/components/items/mails/MailTable.js
- src/pages/mails/Mail.js
- src/pages/mails/MailDetail.js
0517-11시10분-pde -> main
- 메일을 삭제할 수 있는 기능을 추가했습니다.
- 메일이 정상적으로 삭제됩니다.
#83
> [Feature-0517](#83) - 메일 - 메일 삭제

- src/apis/MailAPICalls.js
- src/components/commons/Sidebar.js
- src/components/form/MailForm.js
- src/components/items/mails/MailDeleteModal.js
0517-4시50분-pde -> main
- 메일 전송을 위한 코드를 추가했습니다.
- 메일 전송이 가능하며 전송 후 보낸 메일 목록으로 이동합니다.
> [Feature-0517]() - 메일 - 메일 작성

- src/apis/MailAPICalls.js
- src/components/form/InsertResourceForm.js
- src/components/form/MailForm.js
- src/components/form/UpdateResourceForm.js
- src/components/items/mails/MailContent.js
- src/components/items/mails/MailDeleteModal.js
- src/components/items/mails/SendCancelModal.js
- src/components/lists/mails/ReceiveMail.js
- src/components/lists/resources/ResourceList.js
- src/pages/mails/MailDetail.js
- src/pages/resources/Resources.js
0521-1시5분-pde -> main
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
#이슈번호
> [Feature-0521] - Mail - 메일 수정

- src/components/approvals/AppLineModal.js
- src/components/approvals/RefLineModal.js
- src/components/contents/ApprovalBox.js
- src/pages/Main.js
- src/pages/approvals/Approvals.module.css
- src/pages/approvals/InsertApproval.js
0521 seung -> main
메인화면 전자결재 link, 결재선 참조선 본인선택 방지
#6
> [Feature-0521](#6) - 전자결재등록

- src/components/form/InsertReserveForm.js
- src/components/form/ReserveDetail.js
- src/pages/reserves/Reserve.js
Jay-20240521-v3
- onDateClick 함수에 선택한 자원정보를 매개변수로 전달했습니다.
- 기존에 테스트를 위해 어떤 자원의 달력을 클릭하던지 자원 목록의 첫번째 자원의 예약으로 등록되던 코드를 수정하였습니다.
부모 컴포넌트인 Reserve에서 달력의 날짜를 클릭했을때 실행하는 함수인 onDateClick에 자원정보를 담아서 전달해주었기때문에, 자식 컴포넌트인 InsertReserveForm에서 자원정보를 예약정보와 함께 등록하였습니다.
#이슈번호
#105
> [Feature-0521](#105 ) - InsertReserveForm - 자원예약 등록 업데이트

- src/apis/MailAPICalls.js
- src/apis/ResourceAPICalls.js
- src/components/contents/SearchBarValue.js
- src/components/form/UpdateResourceForm.js
- src/components/items/boards/DeleteModal.js
- src/components/items/mails/MailContent.js
- src/components/items/mails/MailDeleteModal.js
- src/components/items/mails/MailTable.js
- src/components/items/resources/RscDetailContent.js
- src/components/items/resources/RscModal.js
- src/components/lists/mails/ReceiveMail.js
- src/components/lists/mails/SendMail.js
- src/components/lists/resources/ResourceList.js
- src/pages/mails/Mail.js
- src/pages/mails/mail.css
- src/pages/resources/Resources.js
0524-10시-pde -> main
- 자원 페이징 추가
- 메일 렌더링 이슈 수정
- 메일 10개가 넘으면 페이지가 생깁니다.
- 메일 페이지 이동 시 렌더링 이슈가 없습니다.
> [Feature-0524]() - Mail/Resource - 메일 수정, 자원 페이징

- src/apis/MemberAPICalls.js
- src/components/form/UpdatePWForm.js
- src/modules/MemberModule.js
- src/pages/members/Departments.js
- src/pages/members/MyPage.js
ex)240526-hoo-1-> main
ex) 비밀번호 수정 추가
ex) 영문,숫자,특수문자가 사용된 8-25자 사용 가능합니다.
#154
> [Feature-0526] - {MyPage} 비밀번호 수정 #154

- src/components/form/DeleteReserveForm.js
- src/components/form/InsertReserveForm.js
- src/components/form/ReserveDetail.js
- src/components/form/ScheduleDetail.js
- src/pages/Main.js
- src/pages/reserves/Reserve.css
- src/pages/reserves/Reserve.js
- src/pages/schedules/calendar.js
Jay-20240526-v2
메인 페이지 하단 달력 디자인 수정 (버튼, 일정 색상)
- 일정 등록, 수정, 삭제 버튼을 공용 버튼으로 변경하였습니다.
- 메인 페이지 하단 달력 디자인을 수정하여 일정 색상을 타켓 컬러인 빨강색으로 변경하였습니다.
#이슈번호
#131
> [Feature-0526](#131 ) - calendar - 일정 UI 수정

- src/apis/MailAPICalls.js
- src/components/form/InsertBoardForm.js
- src/components/form/InsertNoticeForm.js
- src/components/form/InsertResourceForm.js
- src/components/form/MailForm.js
- src/components/form/UpdateResourceForm.js
- src/components/items/mails/MailDeleteModal.js
- src/components/items/mails/MailTable.js
- src/components/items/resources/RscDetailContent.js
- src/components/items/resources/RscModal.js
- src/components/items/resources/RscRegistModal.js
- src/components/lists/mails/ReceiveMail.js
- src/components/lists/mails/SendMail.js
- src/components/lists/resources/ResourceList.js
- src/layouts/Layout.js
- src/pages/mails/Mail.js
- src/pages/mails/MailDetail.js
- src/pages/mails/mail.css
- src/pages/resources/Resources.js
- src/pages/resources/resource.css
0527-12시12분-pde -> main
- 메일 페이징 수정
- 자원 렌더링 이슈 수정
- 메일이 페이징 처리되어 조회됩니다.
- 자원 조회 시 렌더링 이슈가 수정되어 화면에 보여집니다.
> [Feature-0527](issue 번호) - Mail/Resource - 메일 페이징 수정 진행, 자원 렌더링 수정

- src/apis/MailAPICalls.js
- src/components/commons/Header.js
- src/components/commons/Sidebar.js
- src/components/contents/SearchBarValue.js
- src/components/form/MailForm.js
- src/components/form/UpdateResourceForm.js
- src/components/items/mails/MailDeleteModal.js
- src/components/items/mails/MailTable.js
- src/components/items/resources/RscModal.js
- src/components/lists/mails/ReceiveMail.js
- src/components/lists/mails/SendMail.js
- src/components/lists/resources/ResourceList.js
- src/layouts/Layout.js
- src/modules/MailModule.js
- src/pages/mails/Mail.js
- src/pages/mails/MailDetail.js
- src/pages/mails/mail.css
- src/pages/resources/Resources.js
0527-5시10분-pde -> main
- 메일을 검색할 수 있습니다.
- 읽지 않은 메일의 개수를 알 수 있습니다.
- 메일 검색이 정상적으로 됩니다.
#158
>  [Feature-0527]() - Mails - 읽지 않은 메일 조회, 메일 검색

- src/components/approvals/AppCategory.js
- src/components/approvals/AppCategory.module.css
- src/components/approvals/AppLine.module.css
- src/components/approvals/AppLineModal.js
- src/components/approvals/AppList.js
- src/components/approvals/AppModal.module.css
- src/components/approvals/RefLineModal.js
- src/pages/approvals/ApprovalDetail.js
- src/pages/approvals/Approvals.js
- src/pages/approvals/Approvals.module.css
- src/pages/approvals/InsertApproval.js
0527seung-> main
결재, 참조선의 선택삭제
목록조회에서 카테고리변경시 페이지 검색상태등 변경되지 않던 에러 수정
상세 파일 목록으로 조회
#6 #5 #25
> [Feature-0527]() - 전자결재 - 결재참조선 선택삭제

- src/components/contents/DeleteModal.js
- src/components/form/MailForm.js
- src/components/form/UpdateResourceForm.js
- src/components/items/mails/MailDeleteModal.js
- src/components/items/mails/MailTable.js
- src/components/lists/mails/ReceiveMail.js
- src/pages/mails/Mail.js
- src/pages/mails/mail.css
- src/pages/resources/Resources.js
- src/style.css
ex) 0510-4시-hjk -> main
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
#이슈번호
> [Feature-MMDD](issue 번호) - 기능명 - 자원 상태 변경 또는 삭제 시 메일 내용 수정

- src/apis/ApprovalAPICalls.js
- src/components/approvals/AppCategory.js
- src/components/approvals/AppList.js
- src/components/commons/Sidebar.js
- src/pages/Main.js
- src/pages/approvals/ApprovalDetail.js
- src/pages/approvals/Approvals.js
- src/pages/approvals/InsertApproval.js
0529seung -> main
상세또는 작성페이지에서 뒤로가기를 하면 카테고리가 유지됩니다.
#5
> [Feature-0529](#5) - 전자결재목록 - 카테고리유지

- src/apis/MailAPICalls.js
- src/components/contents/Editor.js
- src/components/form/MailForm.js
- src/components/items/mails/MailContent.js
- src/components/items/mails/MailTable.js
- src/components/items/mails/ReplyMailContent.js
- src/components/lists/mails/ReceiveMail.js
- src/components/lists/mails/SendMail.js
- src/pages/mails/Mail.js
- src/pages/mails/MailDetail.js
0529-12시10분-pde -> main
- 받은 메일 발신자 직급 추가
- 발신자에 이름 + 직급 정보가 같이 나옵니다.
> [Feature-0529] Mail/Resource - 받은 메일 발신자 부서 추가 / 주석 제거

- src/components/form/ReplyMailForm.js
- src/components/items/mails/ReplyMailContent.js
- src/pages/resources/Resources.js
ex) 0510-4시-hjk -> main
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
#이슈번호
> [Feature-0529] Mail - 답장 수정

- src/apis/Api.js
- src/apis/MemberAPICalls.js
ex) 240530-hoo-2 -> main
ex)AWS주소로 request 주소 변경
ex) 이상없습니다.
#183
> [Feature-0530] - {Api} AWS서버 연동

- src/apis/MailAPICalls.js
- src/apis/ResourceAPICalls.js
- src/components/items/mails/MailTable.js
- src/pages/mails/mail.css
0530-5시10분-pde -> main
- 수신자 길이가 길 때 ... 으로 보여집니다.
- 수신자 길이가 길 때 ... 으로 보여집니다.
> [Feature-0530] Mail - 수신자 ... 수정

- src/apis/BoardAPICalls.js
- src/apis/NoticeAPICalls.js
- src/apis/ResourceAPICalls.js
0530-5시30분-hjk -> main
api수정
기존 코드 이상 없음
> [Feature-0530] - api 수정
